[IMP] <rockbotic_custom>: Modificaciión de un campo en el informe de …
avanzosc/custom-addons pull request #351
Opened 2018-07-17 11:25 UTC by gotzonavanzosc

…bajas.

2018-07-17 11:58 UTC, gotzonavanzosc commented
@avanzosc/developers  review please...

2018-07-17 12:38 UTC, Daniel-CA commented on rockbotic_custom/tests/__init__.py
> +# Copyright © 2018 Gotzon Imaz - AvanzOSC
Si no has hecho cambios en el archivo el añadido del copyright sobra.

2018-07-17 12:38 UTC, Daniel-CA commented on rockbotic_custom/tests/test_rockbotic_custom.py
>  # License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html
Si no has hecho cambios en los archivos el añadido del copyright sobra.

2018-07-18 07:49 UTC, gotzonavanzosc commented
@Daniel-CA realizados los cambios solicitados, eskerrik asko

2018-07-18 08:04 UTC, oihane requested changes

2018-07-18 08:04 UTC, oihane commented on rockbotic_custom/__openerp__.py
> +# (c) 2018 Gotzon Imaz - AvanzOSC
Debes poner Copyright

2018-07-18 08:32 UTC, gotzonavanzosc commented
@oihane cambios realizados, eskerrik asko

2018-07-19 08:07 UTC, oihane approved these changes
LGTM

2018-07-19 08:16 UTC, alfredoavanzosc approved these changes
:+1:

2018-07-19 08:16 UTC, merged