[FIX] rockbotic_custom: Fix account invoice 'Effective Date' field ca…
avanzosc/custom-addons pull request #357
Opened 2018-07-25 08:46 UTC by gotzonavanzosc

…lculation.

2018-07-26 11:22 UTC, gotzonavanzosc commented
@avanzosc/developers review please

2018-07-27 07:15 UTC, Daniel-CA requested changes
Falta modificar el cambio de versión del módulo.
https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

2018-07-27 07:15 UTC, Daniel-CA commented on rockbotic_custom/views/account_invoice_view.xml
> +                <field name="number" position="replace"/>
Trata de no utilizar el replace, si no quieres que se muestre un campo ocúltalo con el invisible="1" en los atributos.

2018-08-01 09:38 UTC, gotzonavanzosc commented
@Daniel-CA review please

2018-08-02 06:31 UTC, alfredoavanzosc approved these changes
:+1:

2018-08-02 06:38 UTC, oihane commented on rockbotic_custom/models/account.py
> +    effective_date = fields.Date('Effective date',
No cambies el string de un campo, no es necesario

2018-08-02 06:38 UTC, oihane commented on rockbotic_custom/models/account.py
> +    @api.depends('state')
¿Y si cambia la fecha del pago?

2018-08-02 06:40 UTC, oihane commented on rockbotic_custom/tests/test_rockbotic_custom.py
> +        invoice.state = 'paid'
El estado de una factura no se suele cambiar haciendo un "write" si no que tiene un workflow y según ello se cambia, revisalo y cambialo para que replique ese proceso.

2018-08-02 06:41 UTC, oihane commented on rockbotic_custom/tests/test_rockbotic_custom.py
> +        invoice.payment_ids = [(0, 0, {'name': 'aaaaaaaaaa',
No cambies el formato únicamente, en OCA te lo dirán muchas veces, es meter líneas para revisar que no hay que revisar realmente.

2018-08-02 06:48 UTC, oihane submitted a review, later dismissed
¿Cual es la tarea que corresponde a este PR?

2018-08-02 08:31 UTC, gotzonavanzosc commented on rockbotic_custom/models/account.py
> +    effective_date = fields.Date('Effective date',
En este caso lo quiero cambiar...

2018-08-02 08:44 UTC, gotzonavanzosc commented on rockbotic_custom/models/account.py
> +    effective_date = fields.Date('Effective date',
Es para que coincida con el formato de los demás campos del tree

2018-08-02 08:49 UTC, gotzonavanzosc commented on rockbotic_custom/models/account.py
> +    @api.depends('state')
Se coje la primera fecha de pago al pagar la factura

2018-08-02 08:50 UTC, oihane commented on rockbotic_custom/models/account.py
> +    effective_date = fields.Date('Effective date',
Pero para ello cambia la traducción no el string

Si te fijas en los modulos de Odoo los string en inglés están con todas sus palabras en mayúsculas, te pongo el enlace directo a los campos de la factura:
https://github.com/OCA/OCB/blob/8.0/addons/account/account_invoice.py#L191

Es en las traducciones, y sobretodo por efecto de la comunidad española, que luego se pone solo la primera en mayúscula. Por lo que si es porque guarden coherencia, lo estás rompiendo en inglés.

2018-08-02 08:53 UTC, gotzonavanzosc commented on rockbotic_custom/tests/test_rockbotic_custom.py
> +        invoice.payment_ids = [(0, 0, {'name': 'aaaaaaaaaa',
No entiendo, ¿puedes explicarte un poco mas?

2018-08-02 08:59 UTC, gotzonavanzosc commented on rockbotic_custom/models/account.py
> +    effective_date = fields.Date('Effective date',
ok

2018-08-02 09:01 UTC, oihane commented on rockbotic_custom/tests/test_rockbotic_custom.py
> +        invoice.payment_ids = [(0, 0, {'name': 'aaaaaaaaaa',
![image](https://user-images.githubusercontent.com/2323616/43573743-c2a8e9b0-9642-11e8-8fc0-be8020804308.png)
Es un cambio que no hace nada más que quitar saltos de línea, no cambia el funcionamiento.

2018-08-02 09:10 UTC, gotzonavanzosc commented on rockbotic_custom/tests/test_rockbotic_custom.py
> +        invoice.state = 'paid'
No he tocado el account voucher. No hay ninguna señal del account invoice a la que poder llamar

2018-08-02 10:25 UTC, gotzonavanzosc commented
@avanzosc/developers review please

2018-08-06 08:54 UTC, Daniel-CA approved these changes

2018-08-06 08:54 UTC, merged